export const attendanceRows = [
  {
    id: 1,
    employeeName: 'Ana Cruz',
    department: 'Kitchen',
    shift: 'Morning',
    branch: 'Pantukan Branch',
    date: '2026-04-19',
    timeIn: '08:03',
    timeOut: '17:09',
    status: 'Present',
  },
  {
    id: 2,
    employeeName: 'Mark Dela Rosa',
    department: 'Front of House',
    shift: 'Afternoon',
    branch: 'Panabo Branch',
    date: '2026-04-19',
    timeIn: '08:20',
    timeOut: '17:02',
    status: 'Late',
  },
  {
    id: 3,
    employeeName: 'Lea Santos',
    department: 'Kitchen',
    shift: 'Morning',
    branch: 'Pantukan Branch',
    date: '2026-04-19',
    timeIn: '08:00',
    timeOut: '17:00',
    status: 'Present',
  },
  {
    id: 4,
    employeeName: 'Mia Torres',
    department: 'Service',
    shift: 'Night',
    branch: 'Panabo Branch',
    date: '2026-04-18',
    timeIn: '16:05',
    timeOut: '23:00',
    status: 'Present',
  },
  {
    id: 5,
    employeeName: 'Paolo Luna',
    department: 'Back of House',
    shift: 'Morning',
    branch: 'Pantukan Branch',
    date: '2026-04-18',
    timeIn: '',
    timeOut: '',
    status: 'Absent',
  },
]
