export const plantillaRows = [
  {
    id: 1,
    branch: 'Tagum City',
    position: 'Branch Manager',
    role: 'Operations Leadership',
    baseSalary: 'PHP 45,000',
    allowance: 'PHP 5,000',
  },
  {
    id: 2,
    branch: 'Tagum City',
    position: 'HR Officer',
    role: 'HR Administration',
    baseSalary: 'PHP 28,000',
    allowance: 'PHP 2,500',
  },
  {
    id: 3,
    branch: 'Panabo City',
    position: 'Store Supervisor',
    role: 'Floor Supervision',
    baseSalary: 'PHP 26,000',
    allowance: 'PHP 2,000',
  },
  {
    id: 4,
    branch: 'Panabo City',
    position: 'Cashier',
    role: 'POS Operations',
    baseSalary: 'PHP 18,500',
    allowance: 'PHP 1,200',
  },
  {
    id: 5,
    branch: 'Pantukan',
    position: 'Kitchen Lead',
    role: 'Kitchen Oversight',
    baseSalary: 'PHP 24,000',
    allowance: 'PHP 1,800',
  },
  {
    id: 6,
    branch: 'Pantukan',
    position: 'Dining Staff',
    role: 'Guest Service',
    baseSalary: 'PHP 16,500',
    allowance: 'PHP 1,000',
  },
]
